const translations = {
        English: {
            optionsTitle: "⚙️ Options",
            language: "Language",
            steamReminder: "Steam Reminder",
            discountReminder: "Discount Reminder",
            checkUpdate: "Check Update",
            save: "Save",
            artifacts: "🏺 Artifacts",
            details: "🛸 Details",
            info: "ℹ️ Info",
            ended: "❌ ENDED!",
            open: "🏦 OPEN!",
            loadingArtifacts: "Loading artifacts…",
            replaceable: "✅ Replaceable!",
            noreplace: "❌ Not Replaceable yet!",
            remaining: "remaining",
            noArtifacts: "No artifacts currently equipped.",
            calendarDay: "Calendar Day",
            loginStreak: "Login Streak",
            logoutRelogin: "Logout-Relogin",
            calendarDataNotFound: "Calendar data not found.",
            dailyCalendar: "📆 Daily Calendar",
            dailyCalendarFAQ: "⚠️ Daily Calendar FAQ",
            promotionalCalendar: "Promotional Calendar",
            promotionalCalendarStarted: "📅 Promotional Calendar ✅ STARTED!",
            bonusCalendar: "📆 Daily Calendar",
            bonusDiscord: "📊 Discord Poll",
            bonusSteam: "🎮 Steam Quests",
            bonusTwitch: "📺 Watch Twitch",
            bonusTimesite: "⌛ Time on Site",
            bonusAllARP: "🚀 All ARP",
            bonusDiscount: "🏷️ Market Discount",
            bonusPlaytime: "⌚ SCE Playtime",
            bonusFrag: "🪨 Fragments",
            artifactInfo: "🏺 Artifact Info",
            equippedArtifacts: "⚙️ Equipped Artifacts",
            artifactIssues: "⚠️ Artifact/Fragments Issues",
            upgradeArtifact: "Upgrade Artifact",
            upgradeArtifactDesc: "Artifact without enough Fragments or maxed.",
            changeLinkPrefix: "Change link prefix",
            changeLinkPrefixDesc: "Switch www./na./eu./uk./de./fr./in./anz. to another.",
            logoutReloginDesc: "The whole ultimate answer for all AWAverse.",
            baliFAQ: "⚠️ Ba'li Arches/Gamers Wanted (Time on Site) FAQ",
            baliFAQDesc: "Use Artifact before maxing 5 ARP (Base) for Time on Site",
            chaiFAQ: "⚠️ Chai Stones (Daily Calendar) FAQ",
            chaiFAQDesc1: "Use Artifact before 00:00 UTC of each day.",
            chaiFAQDesc2: "Real value in ARP Log instead of Control Center.",
            chaiFAQDesc3: "Affects any Calendar, like Promotional Advent Calendar.",
            pnFAQ: "⚠️ Pn 295/Sylphin Fission Blade (Steam Quests & Community Events) FAQ",
            pnFAQDesc1: "Use Artifact before starting any Steam Quests. (Due to autocompletion bug)",
            pnFAQDesc2: "Real value in ARP Log instead of Control Center.",
            pnFAQTitle: "Will I get bonus towards Community Event?",
            pnFAQAnswer: "Nope. Only H’erkow Plasma Chamber or Zorathian Renaissance Artifact Set will boost it.",
            fluxFAQ: "⚠️ Flux (Community Event Playtime) FAQ",
            fluxFAQDesc: "Only Playtime affected, nothing else.",
            discountFAQ: "⚠️ Light Warping/Mysterious Text/Omniversal Override/The Stanley Excavation Set (Market Discount) FAQ",
            discountFAQDesc: "If discount not visually up, try the whole ultimate answer for all AWAverse... LOGOUT-RELOGIN!",
            discountFAQTitle: "Does it work with Game Vault? I WANT DISCOUNTS FOR MY KEY!!",
            discountFAQAnswer: "Yep.",
            specialEvents: "📢 Special Events",
            gameVault: "Game Vault",
            GA: "Giveaway",
            communityGA: "Community GA",
            communityEvent: "Community Event",
            controlCenterQuests: "Control Center Quests",
            loadingQuests: "Loading quests data…",
            noneFound: "None found.",
            dailyQuests: "📜 Daily Quests",
            timeOnSite: "⌛ Time on Site",
            watchTwitch: "📺 Watch Twitch",
            steamQuests: "🎮 Steam Quests",
            errorLoadingQuests: "Error loading quests.",
            awaInfos: "👽 AWA Infos",
            awaFAQ: "❔ AWA FAQ",
            arpLog: "ARP Log",
            dailyQuestFAQ: "⚠️ Daily Quest FAQ",
            dailyQuestFAQDesc1: 'Use <a href="/quests" target="_blank">alternative site</a> Daily Quest.',
            dailyQuestFAQDesc2: "Logout-Relogin.",
            dailyCalendarFAQDesc1: "Missing Login Streak Rewards ➡️ Logout-Relogin.",
            dailyCalendarFAQDesc2: "Missing Daily Login Entry ➡️ Non-ARP reward day? Logout-Relogin.",
            steamFAQ: "⚠️ Steam Quests & Community Events FAQ",
            steamFAQDesc1: "Play the game 10–60 min, add any F2P Game/DLC, set Steam Profile public.",
            steamFAQDesc2: "Change your AWA Link Country Prefix (e.g. na. ➡️ www.).",
            steamFAQDesc3: "Retry “Check Game” after a while.",
            progressBarFAQ: "⚠️ Progress bar no updates after 1 hour",
            progressBarFAQDesc1: "Wait 1-2 hours due to delay.",
            progressBarFAQDesc2: "If Steam resets mid-hour, wait longer to update correctly.",
            steamReminderToday: "💡 Remember to switch Steam Artifacts!",
            steamReminderTomorrow: "💡 Remember to switch Steam Artifacts tmr!",
            discountReminderToday: "🛒 Remember to switch Discount Artifacts!",
            discountReminderTomorrow: "🛒 Remember to switch Discount Artifacts tmr!",
            promoCalendarDayAlert: "📅 Promotional Calendar｜✅ Day {claimedCount} of {totalDays}",
            communityEventStarted: "🎮 Community Event ✅ STARTED!",
            questFailed: "❌ Quest failed, please retry.",
            networkErrorQuest: "⚠️ Network error when doing quest.",
            tourWelcomeTitle: "👽 Welcome to Megumin's Alien Center!",
            tourWelcomeContent: "Click “+” to expand the tool.",
            tourArtifactsTitle: "🏺 Artifacts Tab",
            tourArtifactsContent: "View your Artifacts bonuses and manage equipped artifacts here.",
            tourEquippedTitle: "⚙️ Equipped Artifacts",
            tourEquippedContent: "Click to visit your Artifact Room and swap Artifacts.",
            tourIssuesTitle: "⚠️ Have issues with Artifacts?",
            tourIssuesContent: "This panel holds FAQs. Let's see what's in here.",
            tourFAQTitle: "📙 FAQ",
            tourFAQContent: "Several FAQs to answer your questions.",
            tourDetailsTitle: "🛸 Details Tab",
            tourDetailsContent: "Track events, quests, and other daily activities here.",
            tourSpecialEventsTitle: "📢 Special Events",
            tourSpecialEventsContent: "You can visit Game Vault & Community Event by clicking on the titles here.",
            tourWatchTwitchTitle: "📺 Watch Twitch",
            tourWatchTwitchContent: "Click to visit Control Center and see current live streamers.",
            tourInfoTitle: "ℹ️ Info Tab",
            tourInfoContent: "You missed the Tier info? Here they are with many useful AWA related links.",
            tourAwaInfosTitle: "🖥️ AWA Infos",
            tourAwaInfosContent: "Quick links to useful AWA tools & infos.",
            tourAwaFAQsTitle: "❔ AWA FAQs",
            tourAwaFAQsContent: "Some common issues solution can be found here.",
            tourEndTitle: "🎉 And... that's ALL!",
            tourEndContent: "Hope it clears up things and enjoy exploring AWA with Megumin! 💟"
        },
        Español: {
            optionsTitle: "⚙️ Opciones",
            language: "Idioma",
            steamReminder: "Recordatorio de Steam",
            discountReminder: "Recordatorio de Descuento",
            checkUpdate: "Buscar actualizaciones",
            save: "Guardar",
            artifacts: "🏺 Artefactos",
            details: "🛸 Detalles",
            info: "ℹ️ Información",
            ended: "❌ ¡FINALIZADO!",
            open: "🏦 ¡ABIERTO!",
            loadingArtifacts: "Cargando artefactos…",
            replaceable: "✅ ¡Reemplazable!",
            noreplace: "❌ ¡Aún no reemplazable!",
            remaining: "restante",
            noArtifacts: "No hay artefactos equipados.",
            calendarDay: "Día del Calendario",
            loginStreak: "Racha de inicio de sesión",
            logoutRelogin: "Cerrar sesión / Volver a iniciar",
            calendarDataNotFound: "Datos del calendario no encontrados.",
            dailyCalendar: "📆 Calendario Diario",
            dailyCalendarFAQ: "⚠️ Preguntas frecuentes del Calendario Diario",
            promotionalCalendar: "Calendario Promocional",
            promotionalCalendarStarted: "📅 ¡Calendario Promocional ✅ INICIADO!",
            bonusCalendar: "📆 Calendario Diario",
            bonusDiscord: "📊 Encuesta de Discord",
            bonusSteam: "🎮 Misiones de Steam",
            bonusTwitch: "📺 Ver Twitch",
            bonusTimesite: "⌛ Tiempo en el sitio",
            bonusAllARP: "🚀 Todo ARP",
            bonusDiscount: "🏷️ Descuento en el mercado",
            bonusPlaytime: "⌚ Tiempo de juego SCE",
            bonusFrag: "🪨 Fragmentos",
            artifactInfo: "🏺 Información del artefacto",
            equippedArtifacts: "⚙️ Artefactos equipados",
            artifactIssues: "⚠️ Problemas de artefactos/fragmentos",
            upgradeArtifact: "Mejorar artefacto",
            upgradeArtifactDesc: "Artefacto sin suficientes fragmentos o al máximo.",
            changeLinkPrefix: "Cambiar prefijo de enlace",
            changeLinkPrefixDesc: "Cambiar www./na./eu./uk./de./fr./in./anz. por otro.",
            logoutReloginDesc: "La respuesta definitiva para todo AWAverse.",
            baliFAQ: "⚠️ Ba'li Arches/Gamers Wanted (Tiempo en el sitio) FAQ",
            baliFAQDesc: "Usar artefacto antes de alcanzar 5 ARP (Base) para Tiempo en el sitio",
            chaiFAQ: "⚠️ Chai Stones (Calendario diario) FAQ",
            chaiFAQDesc1: "Usar artefacto antes de las 00:00 UTC de cada día.",
            chaiFAQDesc2: "Valor real en el registro ARP en lugar del Centro de control.",
            chaiFAQDesc3: "Afecta cualquier calendario, como el calendario de adviento promocional.",
            pnFAQ: "⚠️ Pn 295/Sylphin Fission Blade (Misiones de Steam y eventos comunitarios) FAQ",
            pnFAQDesc1: "Usar artefacto antes de iniciar cualquier misión de Steam. (Por error de autocompletado)",
            pnFAQDesc2: "Valor real en el registro ARP en lugar del Centro de control.",
            pnFAQTitle: "¿Obtendré bonificación para el evento comunitario?",
            pnFAQAnswer: "No. Solo H’erkow Plasma Chamber o Zorathian Renaissance Artifact Set lo aumentarán.",
            fluxFAQ: "⚠️ Flux (Tiempo de juego en evento comunitario) FAQ",
            fluxFAQDesc: "Solo afecta el tiempo de juego, nada más.",
            discountFAQ: "⚠️ Light Warping/Mysterious Text/Omniversal Override/The Stanley Excavation Set (Descuento de mercado) FAQ",
            discountFAQDesc: "Si el descuento no aparece, prueba la respuesta definitiva... ¡Cerrar sesión y volver a iniciar!",
            discountFAQTitle: "¿Funciona con Game Vault? ¡QUIERO DESCUENTOS PARA MI CLAVE!!",
            discountFAQAnswer: "Sí.",
            specialEvents: "📢 Eventos especiales",
            gameVault: "Bóveda de juegos",
            GA: "Sorteo",
            communityGA: "Sorteo comunitario",
            communityEvent: "Evento comunitario",
            controlCenterQuests: "Misiones del Centro de control",
            loadingQuests: "Cargando datos de misiones…",
            noneFound: "No se encontró nada.",
            dailyQuests: "📜 Misiones diarias",
            timeOnSite: "⌛ Tiempo en el sitio",
            watchTwitch: "📺 Ver Twitch",
            steamQuests: "🎮 Misiones de Steam",
            errorLoadingQuests: "Error al cargar misiones.",
            awaInfos: "👽 Infos AWA",
            awaFAQ: "❔ FAQ de AWA",
            arpLog: "Registro ARP",
            dailyQuestFAQ: "⚠️ FAQ de misión diaria",
            dailyQuestFAQDesc1: 'Usar misión diaria de <a href="/quests" target="_blank">sitio alternativo</a>.',
            dailyQuestFAQDesc2: "Cerrar sesión y volver a iniciar.",
            dailyCalendarFAQDesc1: "Recompensas de racha de inicio de sesión faltantes ➡️ Cerrar sesión y volver a iniciar.",
            dailyCalendarFAQDesc2: "Entrada de inicio de sesión diaria faltante ➡️ ¿Día sin recompensa ARP? Cerrar sesión y volver a iniciar.",
            steamFAQ: "⚠️ FAQ de misiones de Steam y eventos comunitarios",
            steamFAQDesc1: "Jugar de 10 a 60 min, añadir cualquier juego/DLC F2P, poner perfil de Steam público.",
            steamFAQDesc2: "Cambiar el prefijo de país del enlace AWA (ej. na. ➡️ www.).",
            steamFAQDesc3: "Reintentar “Verificar juego” después de un tiempo.",
            progressBarFAQ: "⚠️ La barra de progreso no se actualiza después de 1 hora",
            progressBarFAQDesc1: "Esperar 1-2 horas por retraso.",
            progressBarFAQDesc2: "Si Steam se reinicia a mitad de hora, esperar más para actualizar correctamente.",
            steamReminderToday: "💡 ¡Recuerda cambiar los artefactos de Steam!",
            steamReminderTomorrow: "💡 ¡Recuerda cambiar los artefactos de Steam mañana!",
            discountReminderToday: "🛒 ¡Recuerda cambiar los artefactos de descuento!",
            discountReminderTomorrow: "🛒 ¡Recuerda cambiar los artefactos de descuento mañana!",
            promoCalendarDayAlert: "📅 Calendario promocional｜✅ Día {claimedCount} de {totalDays}",
            communityEventStarted: "🎮 ¡Evento comunitario ✅ INICIADO!",
            questFailed: "❌ La misión falló, inténtalo de nuevo.",
            networkErrorQuest: "⚠️ Error de red al realizar la misión.",
            tourWelcomeTitle: "👽 ¡Bienvenido al Centro Alienígena de Megumin!",
            tourWelcomeContent: "Haz clic en “+” para expandir la herramienta.",
            tourArtifactsTitle: "🏺 Pestaña de artefactos",
            tourArtifactsContent: "Consulta las bonificaciones de tus artefactos y gestiona los equipados aquí.",
            tourEquippedTitle: "⚙️ Artefactos equipados",
            tourEquippedContent: "Haz clic para visitar tu sala de artefactos y cambiarlos.",
            tourIssuesTitle: "⚠️ ¿Problemas con los artefactos?",
            tourIssuesContent: "Este panel contiene las FAQ. Vamos a ver qué hay aquí.",
            tourFAQTitle: "📙 FAQ",
            tourFAQContent: "Varias preguntas frecuentes para responder tus dudas.",
            tourDetailsTitle: "🛸 Pestaña de detalles",
            tourDetailsContent: "Sigue eventos, misiones y otras actividades diarias aquí.",
            tourSpecialEventsTitle: "📢 Eventos especiales",
            tourSpecialEventsContent: "Puedes visitar Game Vault y el evento comunitario haciendo clic en los títulos aquí.",
            tourWatchTwitchTitle: "📺 Ver Twitch",
            tourWatchTwitchContent: "Haz clic para visitar el Centro de control y ver a los streamers en vivo.",
            tourInfoTitle: "ℹ️ Pestaña de información",
            tourInfoContent: "¿Te perdiste la información de niveles? Aquí está junto con muchos enlaces útiles de AWA.",
            tourAwaInfosTitle: "🖥️ Infos AWA",
            tourAwaInfosContent: "Enlaces rápidos a herramientas e información útil de AWA.",
            tourAwaFAQsTitle: "❔ FAQs de AWA",
            tourAwaFAQsContent: "Aquí puedes encontrar soluciones a problemas comunes.",
            tourEndTitle: "🎉 ¡Y... eso es todo!",
            tourEndContent: "¡Espero que aclare las cosas y disfrutes explorando AWA con Megumin! 💟"},
        Português: {
            optionsTitle: "⚙️ Opções",
            language: "Idioma",
            steamReminder: "Lembrete da Steam",
            discountReminder: "Lembrete de Desconto",
            checkUpdate: "Verificar atualizações",
            save: "Salvar",
            artifacts: "🏺 Artefatos",
            details: "🛸 Detalhes",
            info: "ℹ️ Informações",
            ended: "❌ ENCERRADO!",
            open: "🏦 ABERTO!",
            loadingArtifacts: "Carregando artefatos…",
            replaceable: "✅ Substituível!",
            noreplace: "❌ Ainda não substituível",
            remaining: "restante",
            noArtifacts: "Nenhum artefato equipado.",
            calendarDay: "Dia do Calendário",
            loginStreak: "Sequência de login",
            logoutRelogin: "Sair / Entrar novamente",
            calendarDataNotFound: "Dados do calendário não encontrados.",
            dailyCalendar: "📆 Calendário Diário",
            dailyCalendarFAQ: "⚠️ FAQ do Calendário Diário",
            promotionalCalendar: "Calendário Promocional",
            promotionalCalendarStarted: "📅 Calendário Promocional ✅ INICIADO!",
            bonusCalendar: "📆 Calendário Diário",
            bonusDiscord: "📊 Enquete do Discord",
            bonusSteam: "🎮 Missões da Steam",
            bonusTwitch: "📺 Assistir Twitch",
            bonusTimesite: "⌛ Tempo no site",
            bonusAllARP: "🚀 Todo ARP",
            bonusDiscount: "🏷️ Desconto no mercado",
            bonusPlaytime: "⌚ Tempo de jogo SCE",
            bonusFrag: "🪨 Fragmentos",
            artifactInfo: "🏺 Informações do Artefato",
            equippedArtifacts: "⚙️ Artefatos Equipados",
            artifactIssues: "⚠️ Problemas de Artefatos/Fragmentos",
            upgradeArtifact: "Aprimorar Artefato",
            upgradeArtifactDesc: "Artefato sem fragmentos suficientes ou já no nível máximo.",
            changeLinkPrefix: "Alterar prefixo do link",
            changeLinkPrefixDesc: "Trocar www./na./eu./uk./de./fr./in./anz. por outro.",
            logoutReloginDesc: "A resposta definitiva para todo o AWAverse.",
            baliFAQ: "⚠️ Ba'li Arches/Gamers Wanted (Tempo no Site) FAQ",
            baliFAQDesc: "Usar o artefato antes de atingir 5 ARP (Base) para Tempo no Site",
            chaiFAQ: "⚠️ Chai Stones (Calendário Diário) FAQ",
            chaiFAQDesc1: "Usar o artefato antes de 00:00 UTC de cada dia.",
            chaiFAQDesc2: "Valor real no Registro ARP em vez do Centro de Controle.",
            chaiFAQDesc3: "Afeta qualquer calendário, como o Calendário Promocional de Advento.",
            pnFAQ: "⚠️ Pn 295/Sylphin Fission Blade (Missões da Steam e Eventos Comunitários) FAQ",
            pnFAQDesc1: "Usar o artefato antes de iniciar qualquer missão da Steam. (Devido a bug de autocompletar)",
            pnFAQDesc2: "Valor real no Registro ARP em vez do Centro de Controle.",
            pnFAQTitle: "Receberei bônus para o Evento Comunitário?",
            pnFAQAnswer: "Não. Apenas H’erkow Plasma Chamber ou Zorathian Renaissance Artifact Set aumentam.",
            fluxFAQ: "⚠️ Flux (Tempo de Jogo em Evento Comunitário) FAQ",
            fluxFAQDesc: "Apenas o tempo de jogo é afetado, nada mais.",
            discountFAQ: "⚠️ Light Warping/Mysterious Text/Omniversal Override/The Stanley Excavation Set (Desconto no Mercado) FAQ",
            discountFAQDesc: "Se o desconto não aparecer, tente a resposta definitiva... SAIR E ENTRAR NOVAMENTE!",
            discountFAQTitle: "Funciona com Game Vault? QUERO DESCONTOS PARA MINHA CHAVE!!",
            discountFAQAnswer: "Sim.",
            specialEvents: "📢 Eventos Especiais",
            gameVault: "Cofre de Jogos",
            GA: "Sorteio",
            communityGA: "Sorteio comunitário",
            communityEvent: "Evento Comunitário",
            controlCenterQuests: "Missões do Centro de Controle",
            loadingQuests: "Carregando dados das missões…",
            noneFound: "Nada encontrado.",
            dailyQuests: "📜 Missões Diárias",
            timeOnSite: "⌛ Tempo no Site",
            watchTwitch: "📺 Assistir Twitch",
            steamQuests: "🎮 Missões da Steam",
            errorLoadingQuests: "Erro ao carregar missões.",
            awaInfos: "👽 Infos AWA",
            awaFAQ: "❔ FAQ AWA",
            arpLog: "Registro ARP",
            dailyQuestFAQ: "⚠️ FAQ de Missão Diária",
            dailyQuestFAQDesc1: 'Usar missão diária de <a href="/quests" target="_blank">site alternativo</a>.',
            dailyQuestFAQDesc2: "Sair e entrar novamente.",
            dailyCalendarFAQDesc1: "Recompensas de sequência de login ausentes ➡️ Sair e entrar novamente.",
            dailyCalendarFAQDesc2: "Entrada de login diária ausente ➡️ Dia sem recompensa ARP? Sair e entrar novamente.",
            steamFAQ: "⚠️ FAQ de Missões da Steam e Eventos Comunitários",
            steamFAQDesc1: "Jogar de 10 a 60 min, adicionar qualquer jogo/DLC F2P, definir perfil da Steam como público.",
            steamFAQDesc2: "Alterar o prefixo do link AWA (ex.: na. ➡️ www.).",
            steamFAQDesc3: "Tentar novamente “Verificar Jogo” após um tempo.",
            progressBarFAQ: "⚠️ Barra de progresso não atualiza após 1 hora",
            progressBarFAQDesc1: "Aguardar 1-2 horas devido a atraso.",
            progressBarFAQDesc2: "Se a Steam reiniciar no meio da hora, aguardar mais para atualizar corretamente.",
            steamReminderToday: "💡 Lembre-se de trocar os Artefatos da Steam!",
            steamReminderTomorrow: "💡 Lembre-se de trocar os Artefatos da Steam amanhã!",
            discountReminderToday: "🛒 Lembre-se de trocar os Artefatos de Desconto!",
            discountReminderTomorrow: "🛒 Lembre-se de trocar os Artefatos de Desconto amanhã!",
            promoCalendarDayAlert: "📅 Calendário Promocional｜✅ Dia {claimedCount} de {totalDays}",
            communityEventStarted: "🎮 Evento Comunitário ✅ INICIADO!",
            questFailed: "❌ Missão falhou, tente novamente.",
            networkErrorQuest: "⚠️ Erro de rede ao realizar a missão.",
            tourWelcomeTitle: "👽 Bem-vindo ao Centro Alienígena da Megumin!",
            tourWelcomeContent: "Clique em “+” para expandir a ferramenta.",
            tourArtifactsTitle: "🏺 Aba de Artefatos",
            tourArtifactsContent: "Veja os bônus dos seus Artefatos e gerencie os equipados aqui.",
            tourEquippedTitle: "⚙️ Artefatos Equipados",
            tourEquippedContent: "Clique para visitar sua Sala de Artefatos e trocar Artefatos.",
            tourIssuesTitle: "⚠️ Problemas com Artefatos?",
            tourIssuesContent: "Este painel contém FAQs. Vamos ver o que há aqui.",
            tourFAQTitle: "📙 FAQ",
            tourFAQContent: "Várias perguntas frequentes para responder suas dúvidas.",
            tourDetailsTitle: "🛸 Aba de Detalhes",
            tourDetailsContent: "Acompanhe eventos, missões e outras atividades diárias aqui.",
            tourSpecialEventsTitle: "📢 Eventos Especiais",
            tourSpecialEventsContent: "Você pode visitar o Cofre de Jogos e o Evento Comunitário clicando nos títulos aqui.",
            tourWatchTwitchTitle: "📺 Assistir Twitch",
            tourWatchTwitchContent: "Clique para visitar o Centro de Controle e ver os streamers ao vivo.",
            tourInfoTitle: "ℹ️ Aba de Informações",
            tourInfoContent: "Perdeu as informações de nível? Aqui estão com vários links úteis do AWA.",
            tourAwaInfosTitle: "🖥️ Infos AWA",
            tourAwaInfosContent: "Links rápidos para ferramentas e informações úteis do AWA.",
            tourAwaFAQsTitle: "❔ FAQs AWA",
            tourAwaFAQsContent: "Algumas soluções para problemas comuns podem ser encontradas aqui.",
            tourEndTitle: "🎉 E... isso é TUDO!",
            tourEndContent: "Espero que isso esclareça as coisas e aproveite para explorar o AWA com a Megumin! 💟"},
        日本語: {
            optionsTitle: "⚙️ オプション",
            language: "言語",
            steamReminder: "Steam リマインダー",
            discountReminder: "割引リマインダー",
            checkUpdate: "アップデートを確認",
            save: "保存",
            artifacts: "🏺 アーティファクト",
            details: "🛸 詳細",
            info: "ℹ️ 情報",
            ended: "❌ 終了！",
            open: "🏦 開催中！",
            loadingArtifacts: "アーティファクトを読み込み中…",
            replaceable: "✅ 交換可能！",
            noreplace: "❌ まだ交換できません！",
            remaining: "残り",
            noArtifacts: "装備中のアーティファクトはありません。",
            calendarDay: "カレンダーデイ",
            loginStreak: "ログイン連続日数",
            logoutRelogin: "ログアウト・再ログイン",
            calendarDataNotFound: "カレンダーデータが見つかりません。",
            dailyCalendar: "📆 デイリーカレンダー",
            dailyCalendarFAQ: "⚠️ デイリーカレンダー FAQ",
            promotionalCalendar: "プロモーションカレンダー",
            promotionalCalendarStarted: "📅 プロモーションカレンダー ✅ 開始！",
            bonusCalendar: "📆 デイリーカレンダー",
            bonusDiscord: "📊 Discord 投票",
            bonusSteam: "🎮 Steam クエスト",
            bonusTwitch: "📺 Twitch 視聴",
            bonusTimesite: "⌛ サイト滞在時間",
            bonusAllARP: "🚀 全ARP",
            bonusDiscount: "🏷️ マーケット割引",
            bonusPlaytime: "⌚ SCE プレイ時間",
            bonusFrag: "🪨 フラグメント",
            artifactInfo: "🏺 アーティファクト情報",
            equippedArtifacts: "⚙️ 装備中のアーティファクト",
            artifactIssues: "⚠️ アーティファクト／フラグメントの問題",
            upgradeArtifact: "アーティファクトを強化",
            upgradeArtifactDesc: "フラグメント不足または最大レベルです。",
            changeLinkPrefix: "リンクプレフィックスを変更",
            changeLinkPrefixDesc: "www./na./eu./uk./de./fr./in./anz. を別のものに変更。",
            logoutReloginDesc: "AWAverse 全体の究極の解決策。",
            baliFAQ: "⚠️ Ba'li Arches/Gamers Wanted（サイト滞在時間）FAQ",
            baliFAQDesc: "サイト滞在時間のため、5 ARP（基本）に達する前にアーティファクトを使用",
            chaiFAQ: "⚠️ Chai Stones（デイリーカレンダー）FAQ",
            chaiFAQDesc1: "毎日 00:00 UTC 前にアーティファクトを使用。",
            chaiFAQDesc2: "実際の値はコントロールセンターではなく ARP ログに表示。",
            chaiFAQDesc3: "プロモーションアドベントカレンダーなど、あらゆるカレンダーに影響。",
            pnFAQ: "⚠️ Pn 295/Sylphin Fission Blade（Steam クエスト＆コミュニティイベント）FAQ",
            pnFAQDesc1: "Steam クエスト開始前にアーティファクトを使用。（自動完了バグのため）",
            pnFAQDesc2: "実際の値はコントロールセンターではなく ARP ログに表示。",
            pnFAQTitle: "コミュニティイベントのボーナスは得られますか？",
            pnFAQAnswer: "いいえ。H’erkow Plasma Chamber または Zorathian Renaissance Artifact Set のみが増加します。",
            fluxFAQ: "⚠️ Flux（コミュニティイベントプレイ時間）FAQ",
            fluxFAQDesc: "プレイ時間のみ影響し、それ以外はなし。",
            discountFAQ: "⚠️ Light Warping/Mysterious Text/Omniversal Override/The Stanley Excavation Set（マーケット割引）FAQ",
            discountFAQDesc: "割引が表示されない場合、究極の解決策を試す… ログアウト・再ログイン！",
            discountFAQTitle: "Game Vault でも動作しますか？キーの割引が欲しい!!",
            discountFAQAnswer: "はい。",
            specialEvents: "📢 特別イベント",
            gameVault: "ゲームボールト",
            GA: "抽選",
            communityGA: "コミュニティ抽選",
            communityEvent: "コミュニティイベント",
            controlCenterQuests: "コントロールセンタークエスト",
            loadingQuests: "クエストデータを読み込み中…",
            noneFound: "見つかりませんでした。",
            dailyQuests: "📜 デイリークエスト",
            timeOnSite: "⌛ サイト滞在時間",
            watchTwitch: "📺 Twitch を視聴",
            steamQuests: "🎮 Steam クエスト",
            errorLoadingQuests: "クエストの読み込みエラー。",
            awaInfos: "👽 AWA 情報",
            awaFAQ: "❔ AWA FAQ",
            arpLog: "ARP ログ",
            dailyQuestFAQ: "⚠️ デイリークエスト FAQ",
            dailyQuestFAQDesc1: '<a href="/quests" target="_blank">代替サイト</a>のデイリークエストを使用。',
            dailyQuestFAQDesc2: "ログアウト・再ログイン。",
            dailyCalendarFAQDesc1: "ログイン連続報酬がない ➡️ ログアウト・再ログイン。",
            dailyCalendarFAQDesc2: "デイリーログイン記録がない ➡️ 非ARP報酬日？ ログアウト・再ログイン。",
            steamFAQ: "⚠️ Steam クエスト＆コミュニティイベント FAQ",
            steamFAQDesc1: "10〜60分プレイ、任意のF2Pゲーム/DLC追加、Steamプロフィールを公開に設定。",
            steamFAQDesc2: "AWAリンクの国プレフィックスを変更（例: na. ➡️ www.）。",
            steamFAQDesc3: "しばらくしてから「ゲームを確認」を再試行。",
            progressBarFAQ: "⚠️ 1時間後も進行バーが更新されない",
            progressBarFAQDesc1: "遅延のため1〜2時間待つ。",
            progressBarFAQDesc2: "Steam が1時間の途中でリセットされた場合、正しく更新されるまでさらに待つ。",
            steamReminderToday: "💡 Steamアーティファクトを切り替えるのを忘れずに！",
            steamReminderTomorrow: "💡 明日はSteamアーティファクトを切り替えるのを忘れずに！",
            discountReminderToday: "🛒 割引アーティファクトを切り替えるのを忘れずに！",
            discountReminderTomorrow: "🛒 明日は割引アーティファクトを切り替えるのを忘れずに！",
            promoCalendarDayAlert: "📅 プロモーションカレンダー｜✅ {totalDays}日のうち{claimedCount}日目",
            communityEventStarted: "🎮 コミュニティイベント ✅ 開始！",
            questFailed: "❌ クエストに失敗しました。再試行してください。",
            networkErrorQuest: "⚠️ クエスト実行中にネットワークエラーが発生しました。",
            tourWelcomeTitle: "👽 めぐみんのエイリアンセンターへようこそ！",
            tourWelcomeContent: "「+」をクリックしてツールを展開します。",
            tourArtifactsTitle: "🏺 アーティファクトタブ",
            tourArtifactsContent: "アーティファクトのボーナスを確認し、装備を管理します。",
            tourEquippedTitle: "⚙️ 装備中のアーティファクト",
            tourEquippedContent: "クリックしてアーティファクトルームに移動し、アーティファクトを交換します。",
            tourIssuesTitle: "⚠️ アーティファクトに問題がありますか？",
            tourIssuesContent: "このパネルにはFAQがあります。中を見てみましょう。",
            tourFAQTitle: "📙 FAQ",
            tourFAQContent: "質問に答えるためのFAQがいくつかあります。",
            tourDetailsTitle: "🛸 詳細タブ",
            tourDetailsContent: "イベント、クエスト、その他の日常活動をここで追跡します。",
            tourSpecialEventsTitle: "📢 特別イベント",
            tourSpecialEventsContent: "ここでタイトルをクリックすると、Game Vaultやコミュニティイベントにアクセスできます。",
            tourWatchTwitchTitle: "📺 Twitchを見る",
            tourWatchTwitchContent: "クリックしてコントロールセンターに移動し、現在の配信者を確認します。",
            tourInfoTitle: "ℹ️ 情報タブ",
            tourInfoContent: "ティア情報を見逃しましたか？ここに多くの便利なAWA関連リンクと一緒にあります。",
            tourAwaInfosTitle: "🖥️ AWA情報",
            tourAwaInfosContent: "便利なAWAツールや情報へのクイックリンクです。",
            tourAwaFAQsTitle: "❔ AWA FAQ",
            tourAwaFAQsContent: "一般的な問題の解決策がここにあります。",
            tourEndTitle: "🎉 以上で…すべて完了！",
            tourEndContent: "これで疑問が解消し、めぐみんと一緒にAWAを楽しんで探索できることを願っています！💟"},
        繁體中文:{
            optionsTitle: "⚙️ 選項",
            language: "語言",
            steamReminder: "Steam 提醒",
            discountReminder: "折扣提醒",
            checkUpdate: "檢查更新",
            save: "儲存",
            artifacts: "🏺 聖物",
            details: "🛸 詳細",
            info: "ℹ️ 資訊",
            ended: "❌ 已結束！",
            open: "🏦 開放中！",
            loadingArtifacts: "正在載入聖物…",
            replaceable: "✅ 可替換！",
            noreplace: "❌ 尚不可替換！",
            remaining: "剩餘",
            noArtifacts: "目前沒有裝備聖物。",
            calendarDay: "日曆天",
            loginStreak: "連續登入天數",
            logoutRelogin: "登出並重新登入",
            calendarDataNotFound: "找不到日曆資料。",
            dailyCalendar: "📆 每日日曆",
            dailyCalendarFAQ: "⚠️ 每日日曆常見問題",
            promotionalCalendar: "促銷日曆",
            promotionalCalendarStarted: "📅 促銷日曆 ✅ 已開始！",
            bonusCalendar: "📆 每日日曆",
            bonusDiscord: "📊 Discord 投票",
            bonusSteam: "🎮 Steam 任務",
            bonusTwitch: "📺 觀看 Twitch",
            bonusTimesite: "⌛ 網站停留時間",
            bonusAllARP: "🚀 全部 ARP",
            bonusDiscount: "🏷️ 市場折扣",
            bonusPlaytime: "⌚ SCE 遊戲時間",
            bonusFrag: "🪨 碎片",
            artifactInfo: "🏺 聖物資訊",
            equippedArtifacts: "⚙️ 已裝備聖物",
            artifactIssues: "⚠️ 聖物／碎片問題",
            upgradeArtifact: "升級聖物",
            upgradeArtifactDesc: "聖物碎片不足或已達最高等級。",
            changeLinkPrefix: "更改連結前綴",
            changeLinkPrefixDesc: "將 www./na./eu./uk./de./fr./in./anz. 更換為其他。",
            logoutReloginDesc: "AWAverse 的終極解決方案。",
            baliFAQ: "⚠️ Ba'li Arches/Gamers Wanted（網站停留時間）FAQ",
            baliFAQDesc: "在達到 5 ARP（基礎）之前使用聖物以獲得網站停留時間加成",
            chaiFAQ: "⚠️ Chai Stones（每日日曆）FAQ",
            chaiFAQDesc1: "每天 00:00 UTC 前使用聖物。",
            chaiFAQDesc2: "實際數值顯示於 ARP 日誌，而非控制中心。",
            chaiFAQDesc3: "影響所有日曆，例如促銷降臨日曆。",
            pnFAQ: "⚠️ Pn 295/Sylphin Fission Blade（Steam 任務與社群活動）FAQ",
            pnFAQDesc1: "開始任何 Steam 任務前使用聖物。（因自動完成錯誤）",
            pnFAQDesc2: "實際數值顯示於 ARP 日誌，而非控制中心。",
            pnFAQTitle: "我會獲得社群活動加成嗎？",
            pnFAQAnswer: "不會。只有 H’erkow Plasma Chamber 或 Zorathian Renaissance Artifact Set 才會增加。",
            fluxFAQ: "⚠️ Flux（社群活動遊戲時間）FAQ",
            fluxFAQDesc: "僅影響遊戲時間，其他無影響。",
            discountFAQ: "⚠️ Light Warping/Mysterious Text/Omniversal Override/The Stanley Excavation Set（市場折扣）FAQ",
            discountFAQDesc: "若折扣未顯示，請嘗試終極解決方案… 登出並重新登入！",
            discountFAQTitle: "它能用於 Game Vault 嗎？我想要我的金鑰折扣!!",
            discountFAQAnswer: "可以。",
            specialEvents: "📢 特別活動",
            gameVault: "遊戲庫",
            GA: "抽獎",
            communityGA: "社群抽獎",
            communityEvent: "社群活動",
            controlCenterQuests: "控制中心任務",
            loadingQuests: "正在載入任務資料…",
            noneFound: "未找到任何項目。",
            dailyQuests: "📜 每日任務",
            timeOnSite: "⌛ 網站停留時間",
            watchTwitch: "📺 觀看 Twitch",
            steamQuests: "🎮 Steam 任務",
            errorLoadingQuests: "載入任務時發生錯誤。",
            awaInfos: "👽 AWA 資訊",
            awaFAQ: "❔ AWA 常見問題",
            arpLog: "ARP 日誌",
            dailyQuestFAQ: "⚠️ 每日任務 FAQ",
            dailyQuestFAQDesc1: '使用<a href="/quests" target="_blank">替代網站</a>的每日任務。',
            dailyQuestFAQDesc2: "登出並重新登入。",
            dailyCalendarFAQDesc1: "缺少連續登入獎勵 ➡️ 登出並重新登入。",
            dailyCalendarFAQDesc2: "缺少每日登入紀錄 ➡️ 非 ARP 獎勵日？登出並重新登入。",
            steamFAQ: "⚠️ Steam 任務與社群活動 FAQ",
            steamFAQDesc1: "遊玩 10–60 分鐘，新增任何免費遊戲/DLC，將 Steam 個人檔案設為公開。",
            steamFAQDesc2: "更改 AWA 連結國家前綴（例如 na. ➡️ www.）。",
            steamFAQDesc3: "稍後重試「檢查遊戲」。",
            progressBarFAQ: "⚠️ 進度條在 1 小時後未更新",
            progressBarFAQDesc1: "由於延遲，請等待 1–2 小時。",
            progressBarFAQDesc2: "如果 Steam 在中途重置，請再多等一段時間以正確更新。",
            steamReminderToday: "💡 記得切換 Steam 聖物！",
            steamReminderTomorrow: "💡 明天記得切換 Steam 聖物！",
            discountReminderToday: "🛒 記得切換折扣聖物！",
            discountReminderTomorrow: "🛒 明天記得切換折扣聖物！",
            promoCalendarDayAlert: "📅 促銷日曆｜✅ 第 {claimedCount} 天，共 {totalDays} 天",
            communityEventStarted: "🎮 社群活動 ✅ 已開始！",
            questFailed: "❌ 任務失敗，請重試。",
            networkErrorQuest: "⚠️ 執行任務時發生網路錯誤。",
            tourWelcomeTitle: "👽 歡迎來到惠惠的外星人中心！",
            tourWelcomeContent: "點擊「+」展開工具。",
            tourArtifactsTitle: "🏺 聖物分頁",
            tourArtifactsContent: "在此查看聖物加成並管理已裝備的聖物。",
            tourEquippedTitle: "⚙️ 已裝備聖物",
            tourEquippedContent: "點擊前往聖物房並更換聖物。",
            tourIssuesTitle: "⚠️ 聖物有問題嗎？",
            tourIssuesContent: "此面板包含常見問題集，一起來看看。",
            tourFAQTitle: "📙 常見問題",
            tourFAQContent: "多個常見問題的解答。",
            tourDetailsTitle: "🛸 詳細分頁",
            tourDetailsContent: "在此追蹤活動、任務及其他每日活動。",
            tourSpecialEventsTitle: "📢 特別活動",
            tourSpecialEventsContent: "點擊此處的標題可前往遊戲寶庫與社群活動。",
            tourWatchTwitchTitle: "📺 觀看 Twitch",
            tourWatchTwitchContent: "點擊前往控制中心並查看當前直播主。",
            tourInfoTitle: "ℹ️ 資訊分頁",
            tourInfoContent: "錯過等級資訊了嗎？這裡有它們以及許多實用的 AWA 相關連結。",
            tourAwaInfosTitle: "🖥️ AWA 資訊",
            tourAwaInfosContent: "快速連結至實用的 AWA 工具與資訊。",
            tourAwaFAQsTitle: "❔ AWA 常見問題",
            tourAwaFAQsContent: "這裡可以找到一些常見問題的解決方案。",
            tourEndTitle: "🎉 以上…全部完成！",
            tourEndContent: "希望這能解答你的疑問，並與惠惠一起盡情探索 AWA！💟"},
        Français: {
            optionsTitle: "⚙️ Options",
            language: "Langue",
            steamReminder: "Rappel Steam",
            discountReminder: "Rappel de réduction",
            checkUpdate: "Vérifier la mise à jour",
            save: "Enregistrer",
            artifacts: "🏺 Artefacts",
            details: "🛸 Détails",
            info: "ℹ️ Infos",
            ended: "❌ TERMINÉ !",
            open: "🏦 OUVERT !",
            loadingArtifacts: "Chargement des artefacts…",
            replaceable: "✅ Remplaçable !",
            noreplace: "❌ Pas encore remplaçable !",
            remaining: "restant",
            noArtifacts: "Aucun artefact équipé.",
            calendarDay: "Jour du calendrier",
            loginStreak: "Série de connexions",
            logoutRelogin: "Déconnexion / Reconnexion",
            calendarDataNotFound: "Données du calendrier introuvables.",
            dailyCalendar: "📆 Calendrier quotidien",
            dailyCalendarFAQ: "⚠️ FAQ du calendrier quotidien",
            promotionalCalendar: "Calendrier promotionnel",
            promotionalCalendarStarted: "📅 Calendrier promotionnel ✅ DÉMARRÉ !",
            bonusCalendar: "📆 Calendrier quotidien",
            bonusDiscord: "📊 Sondage Discord",
            bonusSteam: "🎮 Quêtes Steam",
            bonusTwitch: "📺 Regarder Twitch",
            bonusTimesite: "⌛ Temps sur le site",
            bonusAllARP: "🚀 Tous les ARP",
            bonusDiscount: "🏷️ Réduction du marché",
            bonusPlaytime: "⌚ Temps de jeu SCE",
            bonusFrag: "🪨 Fragments",
            artifactInfo: "🏺 Infos sur l'artefact",
            equippedArtifacts: "⚙️ Artefacts équipés",
            artifactIssues: "⚠️ Problèmes d'artefacts/fragments",
            upgradeArtifact: "Améliorer l'artefact",
            upgradeArtifactDesc: "Artefact sans fragments suffisants ou déjà au maximum.",
            changeLinkPrefix: "Changer le préfixe du lien",
            changeLinkPrefixDesc: "Remplacer www./na./eu./uk./de./fr./in./anz. par un autre.",
            logoutReloginDesc: "La solution ultime pour tout l'AWAverse.",
            baliFAQ: "⚠️ Ba'li Arches/Gamers Wanted (Temps sur le site) FAQ",
            baliFAQDesc: "Utiliser l'artefact avant d'atteindre 5 ARP (Base) pour le temps sur le site",
            chaiFAQ: "⚠️ Chai Stones (Calendrier quotidien) FAQ",
            chaiFAQDesc1: "Utiliser l'artefact avant 00:00 UTC chaque jour.",
            chaiFAQDesc2: "Valeur réelle dans le journal ARP au lieu du Centre de contrôle.",
            chaiFAQDesc3: "Affecte tout calendrier, comme le calendrier de l'Avent promotionnel.",
            pnFAQ: "⚠️ Pn 295/Sylphin Fission Blade (Quêtes Steam et événements communautaires) FAQ",
            pnFAQDesc1: "Utiliser l'artefact avant de commencer toute quête Steam. (En raison d'un bug d'auto‑complétion)",
            pnFAQDesc2: "Valeur réelle dans le journal ARP au lieu du Centre de contrôle.",
            pnFAQTitle: "Aurais‑je un bonus pour l'événement communautaire ?",
            pnFAQAnswer: "Non. Seuls H’erkow Plasma Chamber ou Zorathian Renaissance Artifact Set l'augmentent.",
            fluxFAQ: "⚠️ Flux (Temps de jeu en événement communautaire) FAQ",
            fluxFAQDesc: "Seul le temps de jeu est affecté, rien d'autre.",
            discountFAQ: "⚠️ Light Warping/Mysterious Text/Omniversal Override/The Stanley Excavation Set (Réduction du marché) FAQ",
            discountFAQDesc: "Si la réduction n'apparaît pas, essayez la solution ultime… DÉCONNEXION/RECONNEXION !",
            discountFAQTitle: "Cela fonctionne avec Game Vault ? JE VEUX DES RÉDUCTIONS POUR MA CLÉ !!",
            discountFAQAnswer: "Oui.",
            specialEvents: "📢 Événements spéciaux",
            gameVault: "Coffre de jeux",
            GA: "Tirage",
            communityGA: "Tirage communautaire",
            communityEvent: "Événement communautaire",
            controlCenterQuests: "Quêtes du Centre de contrôle",
            loadingQuests: "Chargement des données des quêtes…",
            noneFound: "Aucun résultat.",
            dailyQuests: "📜 Quêtes quotidiennes",
            timeOnSite: "⌛ Temps sur le site",
            watchTwitch: "📺 Regarder Twitch",
            steamQuests: "🎮 Quêtes Steam",
            errorLoadingQuests: "Erreur de chargement des quêtes.",
            awaInfos: "👽 Infos AWA",
            awaFAQ: "❔ FAQ AWA",
            arpLog: "Journal ARP",
            dailyQuestFAQ: "⚠️ FAQ de quête quotidienne",
            dailyQuestFAQDesc1: 'Utiliser la quête quotidienne d\'un <a href="/quests" target="_blank">site alternatif</a>.',
            dailyQuestFAQDesc2: "Déconnexion/Reconnexion.",
            dailyCalendarFAQDesc1: "Récompenses de série de connexion manquantes ➡️ Déconnexion/Reconnexion.",
            dailyCalendarFAQDesc2: "Entrée de connexion quotidienne manquante ➡️ Jour sans récompense ARP ? Déconnexion/Reconnexion.",
            steamFAQ: "⚠️ FAQ des quêtes Steam et événements communautaires",
            steamFAQDesc1: "Jouer 10–60 min, ajouter un jeu/DLC F2P, mettre le profil Steam en public.",
            steamFAQDesc2: "Changer le préfixe de pays du lien AWA (ex. na. ➡️ www.).",
            steamFAQDesc3: "Réessayer « Vérifier le jeu » après un moment.",
            progressBarFAQ: "⚠️ La barre de progression ne se met pas à jour après 1 heure",
            progressBarFAQDesc1: "Attendre 1–2 heures en raison du délai.",
            progressBarFAQDesc2: "Si Steam se réinitialise en milieu d'heure, attendre plus longtemps pour une mise à jour correcte.",
            steamReminderToday: "💡 Pensez à changer les artefacts Steam !",
            steamReminderTomorrow: "💡 Demain, pensez à changer les artefacts Steam !",
            discountReminderToday: "🛒 Pensez à changer les artefacts de réduction !",
            discountReminderTomorrow: "🛒 Demain, pensez à changer les artefacts de réduction !",
            promoCalendarDayAlert: "📅 Calendrier promotionnel｜✅ Jour {claimedCount} sur {totalDays}",
            communityEventStarted: "🎮 Événement communautaire ✅ DÉMARRÉ !",
            questFailed: "❌ Échec de la quête, veuillez réessayer.",
            networkErrorQuest: "⚠️ Erreur réseau lors de l'exécution de la quête.",
            tourWelcomeTitle: "👽 Bienvenue au Centre Alien de Megumin !",
            tourWelcomeContent: "Cliquez sur « + » pour développer l'outil.",
            tourArtifactsTitle: "🏺 Onglet Artefacts",
            tourArtifactsContent: "Consultez les bonus de vos artefacts et gérez ceux équipés ici.",
            tourEquippedTitle: "⚙️ Artefacts équipés",
            tourEquippedContent: "Cliquez pour visiter votre salle d'artefacts et les échanger.",
            tourIssuesTitle: "⚠️ Des problèmes avec les artefacts ?",
            tourIssuesContent: "Ce panneau contient des FAQ. Voyons ce qu'il y a dedans.",
            tourFAQTitle: "📙 FAQ",
            tourFAQContent: "Plusieurs FAQ pour répondre à vos questions.",
            tourDetailsTitle: "🛸 Onglet Détails",
            tourDetailsContent: "Suivez ici les événements, quêtes et autres activités quotidiennes.",
            tourSpecialEventsTitle: "📢 Événements spéciaux",
            tourSpecialEventsContent: "Vous pouvez visiter le Coffre de jeux et l'Événement communautaire en cliquant sur les titres ici.",
            tourWatchTwitchTitle: "📺 Regarder Twitch",
            tourWatchTwitchContent: "Cliquez pour visiter le Centre de contrôle et voir les streamers en direct.",
            tourInfoTitle: "ℹ️ Onglet Infos",
            tourInfoContent: "Vous avez manqué les infos de niveau ? Les voici avec de nombreux liens utiles liés à AWA.",
            tourAwaInfosTitle: "🖥️ Infos AWA",
            tourAwaInfosContent: "Liens rapides vers des outils et infos utiles d'AWA.",
            tourAwaFAQsTitle: "❔ FAQ AWA",
            tourAwaFAQsContent: "Vous trouverez ici des solutions à des problèmes courants.",
            tourEndTitle: "🎉 Et... c'est TOUT !",
            tourEndContent: "J'espère que cela clarifie les choses et que vous apprécierez explorer AWA avec Megumin ! 💟"}}